### ISSUE TITLE
Error in installation instructions

### ISSUE THREAD

**Issue by dsloyer74** [TheSpaghettiDetective/tsd-moonraker#10] opened 2022-01-21 02:17 UTC
pwd is ~/tsd-moonraker per "cd tsd-moonraker" in previous step
source venv/bin/activate fails with directory not found

python3 venv create step was run per instructions prior to these steps with no stderr

**Comment by scuk23** [comment] 2022-01-21 16:05
https://github.com/TheSpaghettiDetective/tsd-moonraker/issues/8

**Comment by raymondh2** [comment] 2022-01-21 16:13
Duplicate of #8

**Closed by raymondh2** 2022-01-21 16:13 UTC
